lab7_csharp/Pizzario.Web/Controllers/MenuController.cs
/* (C) 2014-2016, Sergei Zaychenko, NURE, Kharkiv, Ukraine */

using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Practices.Unity;

using Pizzario.Dto;
using Pizzario.Service;
using Pizzario.Web.Models;


namespace Pizzario.Web.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index ()
        {
            var viewModel = new MenuViewModel();
            viewModel.Products = GetProductslist();
            viewModel.Sizes = GetProductSizesList();
            viewModel.ProductPrices = GetProductPricesMap();

            return View( viewModel );
        }

        private IList< ProductDto > GetProductslist ()
        {
            IList< Guid > productIds = productService.ViewAll();

            IList< ProductDto > result = new List< ProductDto >();
            foreach ( var productId in productIds )
                result.Add( productService.View( productId ) );

            return result.OrderBy( p => p.Name ).ToList();
        }


        private List< ProductSizeDto > GetProductSizesList ()
        {
            IList< Guid > productSizeIds = productSizeService.ViewAll();

            IList< ProductSizeDto > result = new List< ProductSizeDto >();
            foreach ( var productSizeId in productSizeIds )
                result.Add( productSizeService.View( productSizeId ) );

            return result.OrderBy( sz => sz.Diameter ).ToList();
        }


        private IDictionary< Guid, IDictionary< Guid, decimal > > GetProductPricesMap ()
        {
            var result = new Dictionary< Guid, IDictionary< Guid, decimal > >();

            foreach ( Guid productId in productService.ViewAll() )
            {
                ProductPricingDto pricingDto = productService.ViewPrices( productId );
                result.Add( productId, pricingDto.PricesBySizeId );
            }

            return result;
        }


        [ Dependency ]
        protected IProductService productService { get; set; }

        [ Dependency ]
        protected IProductSizeService productSizeService { get; set; }
    }
}

lab7_csharp/Pizzario.Web/Views/Shared/_BasicLayout.cshtml
@*(C) 2014-2016, Sergei Zaychenko, NURE, Kharkiv, Ukraine*@

@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Localization;

@inject IStringLocalizer< Pizzario.Web.Resources > Localizer

@{
    var requestCulture = Context.Features.Get< IRequestCultureFeature >();
    var language = requestCulture.RequestCulture.Culture.TwoLetterISOLanguageName;
}
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/lib/bootstrapValidator/dist/css/bootstrapValidator.min.css" />
    <link rel="stylesheet" href="/lib/languages/languages.min.css" />

    <link rel="stylesheet" href="/css/main.css" />

    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/lib/bootstrapValidator/dist/js/bootstrapValidator.min.js"></script>
    <script src="/lib/ztoast/ztoast.min.js"></script>
    
    <script src="/js/set_locale.js"></script>
    <script src="/js/cart.js"></script>
    <script src="/js/track_order.js"></script>

    @RenderSection( "HeaderContent", required: false )

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <img alt="Brand" src="~/images/pizzario.jpg">
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li @if ( ViewBag.ActiveLink == "menu" ) { 
                                @: class="active" 
                            }>
                            <a href="@Url.Action( "Index", "Menu" )"><i class="glyphicon glyphicon-list-alt"></i> @Localizer[ "Menu" ]</a> 
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><span class="lang-sm lang-lbl-full" lang="@language"></span> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><button type="button" class="btn btn-link" onclick="setLocale('en');"><span class="lang-sm lang-lbl-full" lang="en"></span></button></li>
                                <li><button type="button" class="btn btn-link" onclick="setLocale('ru');"><span class="lang-sm lang-lbl-full" lang="ru"></span></button></li>
                                <li><button type="button" class="btn btn-link" onclick="setLocale('uk');"><span class="lang-sm lang-lbl-full" lang="uk"></span></button></li>
                            </ul>
                        </li>
                    </ul>
                    <div class="navbar-right">
                        <button type="submit" class="btn btn-default navbar-btn" data-toggle="modal" data-target="#trackOrderModal">
                            <i class="glyphicon glyphicon-search"></i> @Localizer[ "Track Order" ]
                        </button>
                        <button type="button" class="btn btn-default navbar-btn" id="btnCart" data-toggle="modal" data-target="#addToCartModal">
                            <span class="glyphicon glyphicon-shopping-cart"></span> @Localizer[ "Cart" ]
                            <span class="badge" id="badgeCart" hidden></span>
                        </button>
                    </div>
                </div>
            </div>
        </nav>
        
        @RenderBody()

        <div class="modal fade" id="addToCartModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">
                            <span class="glyphicon glyphicon-shopping-cart"></span> @Localizer[ "Cart" ]
                        </h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success pull-left" id="btnCheckout" onclick="checkoutCart();">
                            <span class="glyphicon glyphicon-usd"></span> @Localizer[ "Checkout" ]
                        </button>
                        <button type="button" class="btn btn-link" id="btnClear" onclick="clearCart()">@Localizer[ "Clear" ]</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">@Localizer[ "Cancel" ]</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="trackOrderModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">
                            <span class="glyphicon glyphicon-search"></span> @Localizer[ "Track Order" ]
                        </h4>
                    </div>
                    <div class="modal-body">
                        <form id="trackOrderForm" class="form-horizontal" action="/trackorder/" method="post">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="inputTrackOrderId">@Localizer[ "Order ID" ]</label>
                                <div class="col-sm-9">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-tag"></i></span>
                                        <input class="form-control" type="text" id="inputTrackOrderId" name="inputTrackOrderId" placeholder="@Localizer[ "Order ID" ]" />
                                    </div>
                                    <span class="help-block">@Localizer[ "Example" ]: e2ecad90-51ae-4e9a-a6bf-09e31a962dc4</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="inputTrackOrderEmail">@Localizer[ "E-mail" ]</label>
                                <div class="col-sm-9">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                        <input class="form-control" type="text" id="inputTrackOrderEmail" name="inputTrackOrderEmail" placeholder="@Localizer[ "E-mail" ]" />
                                    </div>
                                    <span class="help-block">@Localizer[ "Example" ]: john.smith@gmail.com</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-9 col-sm-offset-2">
                                    <button type="submit" class="btn btn-success">
                                        <span class="glyphicon glyphicon-search"></span> @Localizer[ "Track" ]
                                    </button>
                                    <button type="button" class="btn btn-default pull-right" data-dismiss="modal">
                                        <span class="glyphicon glyphicon-remove"></span> @Localizer[ "Cancel" ]
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>